[package]
name = "koumakan"
version = "0.1.0"
authors = ["Zachary Neely <zrussellneely@gmail.com>"]
edition = "2018"

[dependencies.chrono]
version = "0.4"

[dependencies.uuid]
version = "0.8"
features = ["guid"] # enables parsing winapi GUIDs

[dependencies.winapi]
version = "0.3"
features = [
    "errhandlingapi",
    "handleapi",
    "ioapiset",
    "impl-default",
    "processthreadsapi",
    "securitybaseapi",
    "winbase",
    "winerror",
    "winioctl",
    "winnt",
]